version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:13-alpine
    container_name: swissairdry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-swissairdry}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PGPORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MQTT Broker (Mosquitto)
  mqtt:
    image: eclipse-mosquitto:2
    container_name: swissairdry-mqtt
    restart: unless-stopped
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSockets
    command: "mosquitto -c /mosquitto/config/mosquitto.conf"

  # API and Web Interface
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: swissairdry-api
    restart: unless-stopped
    depends_on:
      - postgres
      - mqtt
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=${PGDATABASE:-swissairdry}
      - DATABASE_URL=postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@postgres:5432/${PGDATABASE:-swissairdry}
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
    ports:
      - "8000:8000"  # API
      - "5000:5000"  # Web Interface
    volumes:
      - .:/app
      - ./firmware:/app/firmware

  # MQTT to Database Bridge
  mqtt-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: swissairdry-mqtt-bridge
    restart: unless-stopped
    depends_on:
      - postgres
      - mqtt
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:-postgres}
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=${PGDATABASE:-swissairdry}
      - DATABASE_URL=postgresql://${PGUSER:-postgres}:${PGPASSWORD:-postgres}@postgres:5432/${PGDATABASE:-swissairdry}
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
    volumes:
      - ./mqtt_bridge:/app

volumes:
  postgres_data:
